[package]
name = "erc20_anon_gov"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.18.0"
scarb-version = "2.18.0"

[dependencies]
starknet = "2.18.0"
openzeppelin = { git = "https://github.com/PhilippeR26/OZ-contracts", branch = "anonym-vote" }

[dev-dependencies]
snforge_std = "0.60.0"
assert_macros = "2.18.0"

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "all"
sierra = true
casm = true

[[test]]
name = "erc20_anon_gov_tests"
source-path = "tests/lib.cairo"
test-type = "integration"
build-external-contracts = ["erc20_anon_gov::token::GovToken", "erc20_anon_gov::governor::AnonGovernor"]

[profile.dev.cairo] 
add-statements-code-locations-debug-info = true
add-statements-functions-debug-info = true
add-functions-debug-info = true
skip-optimizations = true

